name: pypsa-gui2
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pypsa=1.1.2
  - highspy=1.13.1
  - numpy=2.4.2
  - pandas=3.0.3
  - xarray=2026.4.0
  - scipy=1.17.1
  - linopy=0.7.0
  - openpyxl=3.1.5
  - netcdf4=1.7.3
  - matplotlib=3.10.8
  - pyqt=6.11.0
  - pyqtwebengine=6.11.0
